am_backoffice:
    resource: "@AMBackofficeBundle/Resources/config/routing.yml"
    prefix:   /

am_site:
    resource: "@AMSiteBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:    /login
    defaults:
        _controller: AMUserBundle:Security:login

login_check:
    path:    /login_check

logout:
    path:    /logout