am_backoffice_index:
    path:     /bo/
    defaults: { _controller: AMBackofficeBundle:Backoffice:index }

am_backoffice_users:
    path:    /bo/users/{id}
    defaults: { _controller: AMBackofficeBundle:Backoffice:users }

am_backoffice_changeusers:
    path: /bo/changeusers/{id}
    defaults: { _controller: AMBackofficeBundle:Backoffice:changeusers }

am_backoffice_addpost:
   path:    /bo/addpost
   defaults: { _controller: AMBackofficeBundle:Backoffice:addpost }

am_backoffice_addaddpost:
   path:    /bo/addaddpost
   defaults: { _controller: AMBackofficeBundle:Backoffice:addaddpost }

am_backoffice_aboutme:
   path:    /bo/myabout
   defaults: { _controller: AMBackofficeBundle:Backoffice:aboutme }

am_backoffice_changemyabout:
    path:    /bo/changeabout/{id}
    defaults: { _controller: AMBackofficeBundle:Backoffice:changemyabout }

am_backoffice_myposts:
   path:    /bo/myposts
   defaults: { _controller: AMBackofficeBundle:Backoffice:myposts }

am_backoffice_changemypost:
    path:   /bo/changemypost/{id}
    defaults: { _controller: AMBackofficeBundle:Backoffice:changemypost }

am_backoffice_deletemypost:
    path:    /bo/deletemypost/{id}
    defaults: { _controller: AMBackofficeBundle:Backoffice:deletemypost }

am_backoffice_usertemp:
   path:    /bo/inscription
   defaults: { _controller: AMBackofficeBundle:Backoffice:usertemp }

am_backoffice_removeusertemp:
    path:    /bo/removeusertemp/{id}
    defaults: { _controller: AMBackofficeBundle:Backoffice:removeusertemp }

am_backoffice_validateusertemp:
    path:    /bo/validateusertemp/{id}
    defaults: { _controller: AMBackofficeBundle:Backoffice:validateusertemp }

am_backoffice_mymails:
   path:    /bo/messagerie
   defaults: { _controller: AMBackofficeBundle:Backoffice:mail }

am_backoffice_sendmail:
    path:    /bo/sendmail{firstname}
    defaults: { _controller: AMBackofficeBundle:Backoffice:sendmail }

am_backoffice_removemail:
   path:    /bo/removemail/{id}
   defaults: { _controller: AMBackofficeBundle:Backoffice:removemail }