<?php

namespace AM\BackofficeBundle\Repository;

/**
 * AboutMeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutMeRepository extends \Doctrine\ORM\EntityRepository
{
}
