<?php

namespace AM\BackofficeBundle\Repository;

/**
 * UsertempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsertempRepository extends \Doctrine\ORM\EntityRepository
{
}
